// <auto-generated />
using System;
using HRMS.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMS.DataAccess.Migrations
{
    [DbContext(typeof(HrmsAppDbContext))]
    [Migration("20231219121341_LeaveAndSalary")]
    partial class LeaveAndSalary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMS.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alternate_Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Candidate_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Candidate_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Candidate_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_of_Brith")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_Proof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job_Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("interview_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("HRMS.Models.CandidateEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year_Of_Passing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_Percentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_Active")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("tbl_CandidateQualification");
                });

            modelBuilder.Entity("HRMS.Models.CandidateExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Current_CTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expected_CTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year_Of_Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_Active")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("tbl_CandidateExperience");
                });

            modelBuilder.Entity("HRMS.Models.CityMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_CityMaster");
                });

            modelBuilder.Entity("HRMS.Models.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tbl_Department");
                });

            modelBuilder.Entity("HRMS.Models.Experiences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_Experience");
                });

            modelBuilder.Entity("HRMS.Models.JobRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_JobRole");
                });

            modelBuilder.Entity("HRMS.Models.LeavePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LeavePolicyId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<int?>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeavePolicyId");

                    b.ToTable("tbl_Leavepolicy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2380),
                            EmployeeId = "Thlai123Dotnet",
                            IsActive = true,
                            LeavePolicyId = 1,
                            ModifiedBy = 0,
                            NoOfDays = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2383),
                            EmployeeId = "Thlai123Dotnet",
                            IsActive = true,
                            LeavePolicyId = 2,
                            ModifiedBy = 0,
                            NoOfDays = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2385),
                            EmployeeId = "Thlai123Dotnet",
                            IsActive = true,
                            LeavePolicyId = 3,
                            ModifiedBy = 0,
                            NoOfDays = 2
                        });
                });

            modelBuilder.Entity("HRMS.Models.LeavePolicyMaster", b =>
                {
                    b.Property<int>("LeavePolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeavePolicyId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LeavePolicys")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("LeavePolicyId");

                    b.ToTable("tbl_LeavePolicyMaster");

                    b.HasData(
                        new
                        {
                            LeavePolicyId = 1,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2133),
                            IsActive = true,
                            LeavePolicys = "Casual",
                            ModifiedBy = 0,
                            ShortName = "CL"
                        },
                        new
                        {
                            LeavePolicyId = 2,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2144),
                            IsActive = true,
                            LeavePolicys = "Medical",
                            ModifiedBy = 0,
                            ShortName = "ML"
                        },
                        new
                        {
                            LeavePolicyId = 3,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2146),
                            IsActive = false,
                            LeavePolicys = "Special Leave",
                            ModifiedBy = 0,
                            ShortName = "SL"
                        });
                });

            modelBuilder.Entity("HRMS.Models.PayElementMaster", b =>
                {
                    b.Property<int>("PayElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayElementId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayElements")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PayElementId");

                    b.ToTable("tbl_PayElementMaster");

                    b.HasData(
                        new
                        {
                            PayElementId = 1,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2328),
                            IsActive = true,
                            ModifiedBy = 0,
                            PayElements = "Basic Salary",
                            ShortName = "Basic"
                        },
                        new
                        {
                            PayElementId = 2,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2331),
                            IsActive = true,
                            ModifiedBy = 0,
                            PayElements = "Convaeyance Allownce",
                            ShortName = "CA"
                        },
                        new
                        {
                            PayElementId = 3,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2333),
                            IsActive = false,
                            ModifiedBy = 0,
                            PayElements = "House Rent Allownce",
                            ShortName = "Rent"
                        },
                        new
                        {
                            PayElementId = 4,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2334),
                            IsActive = false,
                            ModifiedBy = 0,
                            PayElements = "Special Allownce",
                            ShortName = "Special"
                        });
                });

            modelBuilder.Entity("HRMS.Models.Qualifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Percentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("year_Of_Passing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_Qualification");
                });

            modelBuilder.Entity("HRMS.Models.RoleMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_RoleMaster");
                });

            modelBuilder.Entity("HRMS.Models.SalaryStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Addition")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Deduction")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PayElementId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalValue")
                        .HasColumnType("int");

                    b.Property<int?>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PayElementId");

                    b.ToTable("tbl_SalaryStructure");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Addition = 2000,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2354),
                            Deduction = 2000,
                            EmployeeId = "Thlai123Dotnet",
                            IsActive = true,
                            ModifiedBy = 0,
                            PayElementId = 1,
                            TotalValue = 10000
                        },
                        new
                        {
                            Id = 2,
                            Addition = 2000,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2357),
                            Deduction = 2000,
                            EmployeeId = "Thlai123Dotnet",
                            IsActive = true,
                            ModifiedBy = 0,
                            PayElementId = 2,
                            TotalValue = 10000
                        },
                        new
                        {
                            Id = 3,
                            Addition = 2000,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2023, 12, 19, 17, 43, 41, 396, DateTimeKind.Local).AddTicks(2359),
                            Deduction = 2000,
                            EmployeeId = "Thlai123Dotnet",
                            IsActive = true,
                            ModifiedBy = 0,
                            PayElementId = 2,
                            TotalValue = 10000
                        });
                });

            modelBuilder.Entity("HRMS.Models.StateMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_StateMaster");
                });

            modelBuilder.Entity("HRMS.Models.StatusMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_StatusMaster");
                });

            modelBuilder.Entity("HRMS.Models.Uploadfiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Is_Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Upload")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_CandidateDocument");
                });

            modelBuilder.Entity("HRMS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_User");
                });

            modelBuilder.Entity("HRMS.Models.CandidateEducation", b =>
                {
                    b.HasOne("HRMS.Models.Candidate", "Candidate")
                        .WithMany("CandidateEducation")
                        .HasForeignKey("CandidateId");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("HRMS.Models.CandidateExperience", b =>
                {
                    b.HasOne("HRMS.Models.Candidate", "Candidate")
                        .WithMany("CandidateExperience")
                        .HasForeignKey("CandidateId");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("HRMS.Models.LeavePolicy", b =>
                {
                    b.HasOne("HRMS.Models.LeavePolicyMaster", "LeavePolicyMaster")
                        .WithMany()
                        .HasForeignKey("LeavePolicyId");

                    b.Navigation("LeavePolicyMaster");
                });

            modelBuilder.Entity("HRMS.Models.SalaryStructure", b =>
                {
                    b.HasOne("HRMS.Models.PayElementMaster", "PayElementMaster")
                        .WithMany()
                        .HasForeignKey("PayElementId");

                    b.Navigation("PayElementMaster");
                });

            modelBuilder.Entity("HRMS.Models.Candidate", b =>
                {
                    b.Navigation("CandidateEducation");

                    b.Navigation("CandidateExperience");
                });
#pragma warning restore 612, 618
        }
    }
}
